### Get all

GET https://localhost:7132/api/species

### Get one
GET https://localhost:7132/pizza/4

### Create

POST https://localhost:7132/pizza/
Content-Type: application/json

{"name":"Salami", "isGlutenFree":false}


### Create full

POST https://localhost:7132/pizza/
Content-Type: application/json

{
  "name": "BBQ Beef",
  "sauce": {
    "name": "BBQ",
    "isVegan": false
  },
  "toppings": [
    {
      "name": "Smoked Beef Brisket",
      "calories": 250
    }
  ]
}

### Update sauce

PUT https://localhost:7132/pizza/4/updatesauce?sauceId=2

### add topping

PUT https://localhost:7132/pizza/4/addtopping?toppingId=2

### Delete

DELETE https://localhost:7132/pizza/3

### Get all trainer

GET https://localhost:7132/api/trainers/

### Get one trainer
GET https://localhost:7132/api/trainers/901311d2-d41b-4e1a-9238-51842a5684ac

### Create trainer

POST https://localhost:7132/api/trainers/
Content-Type: application/json

{
  "name": "Ash Ketchum",
  "email": "ash@ketchum.jp"
}

### Get all cached species

GET https://localhost:7132/api/species/

### Get species by id

GET https://localhost:7132/api/species/1

### Create pokemon
######  TODO target request
POST https://localhost:7132/api/pokemons/
Content-Type: application/json

{
  "trainerId": "111-111-111-111",
  "speciesId": 132,
  "level": 5,
  "nickname": "Scytherino"
}